In [3]:
%%capture
!pip install pandas openpyxl --dry-run

In [4]:
import pandas as pd
import xlrd

In [5]:
# Load Excel file
df = pd.read_excel('2021_Global_Nutrition_Report_Dataset_6YAamkd.xlsx', engine='openpyxl', sheet_name = None)
df

{'Introduction':    Unnamed: 0 2021 Global Nutrition Report: The state of global nutrition
 0         NaN                          globalnutritionreport.org
 1         NaN                                                NaN
 2         NaN  For full definitions and sources, see the 2021...         ,
 'Indicator descriptions':                    section                            variable
 0                 Overview                       anaemia_track  \
 1                 Overview                           lbw_track
 2                 Overview                           ebf_track
 3                 Overview              under_5_stunting_track
 4                 Overview               under_5_wasting_track
 ..                     ...                                 ...
 122  Environmental impacts          planetary_impacts_Cropland
 123  Environmental impacts        planetary_impacts_Freshwater
 124  Environmental impacts  planetary_impacts_Greenhouse gases
 125  Environmental impacts          planetary_impacts_Nitrogen
 126  Environmental impacts        planetary_impacts_Phosphorus

                                            description
 0    Progress against global anaemia target (status...
 1    Progress against global low birth weight targe...
 2    Progress against global exclusive breastfeedin...
 3    Progress against global child stunting target ...
 4    Progress against global child wasting target (...
 ..                                                 ...
 122  Food system impact on planetary boundary value...
 123  Food system impact on planetary boundary value...
 124  Food system impact on planetary boundary value...
 125  Food system impact on planetary boundary value...
 126  Food system impact on planetary boundary value...

 [127 rows x 3 columns],
 'Country overview':     iso3                             country disaggregation  disagg.value
 0    AFG                         Afghanistan            all           NaN  \
 1    ALB                             Albania            all           NaN
 2    DZA                             Algeria            all           NaN
 3    AND                             Andorra            all           NaN
 4    AGO                              Angola            all           NaN
 ..   ...                                 ...            ...           ...
 189  VEN  Venezuela (Bolivarian Republic of)            all           NaN
 190  VNM                            Viet Nam            all           NaN
 191  YEM                               Yemen            all           NaN
 192  ZMB                              Zambia            all           NaN
 193  ZWE                            Zimbabwe            all           NaN

                               region           subregion
 0                               Asia       Southern Asia  \
 1                             Europe     Southern Europe
 2                             Africa     Northern Africa
 3                             Europe     Southern Europe
 4                             Africa       Middle Africa
 ..                               ...                 ...
 189  Latin America and the Caribbean       South America
 190                             Asia  South-eastern Asia
 191                             Asia        Western Asia
 192                           Africa      Eastern Africa
 193                           Africa      Eastern Africa

                                     section    under_5_stunting_track
 0    The burden of malnutrition at a glance             Some progress  \
 1    The burden of malnutrition at a glance                 On course
 2    The burden of malnutrition at a glance             Some progress
 3    The burden of malnutrition at a glance                   No data
 4    The burden of malnutrition at a glance  No progress or worsening
 ..                                      ...                       ...
 189  The burden of malnutrition at a glance             Some progress
 190  The burden of malnutrition at a glance             Some progress
 191  The burden of malnutrition at a glance             Some progress
 192  The burden of malnutrition at a glance             Some progress
 193  The burden of malnutrition at a glance                 On course

                 anaemia_track                 lbw_track
 0    No progress or worsening                   No data  \
 1    No progress or worsening                 On course
 2    No progress or worsening  No progress or worsening
 3    No progress or worsening  No progress or worsening
 4    No progress or worsening             Some progress
 ..                        ...                       ...
 189  No progress or worsening  No progress or worsening
 190  No progress or worsening             Some progress
 191  No progress or worsening                   No data
 192  No progress or worsening             Some progress
 193             Some progress  No progress or worsening

     under_5_overweight_track                 ebf_track
 0                  On course                 On course  \
 1                  On course  No progress or worsening
 2                  On course  No progress or worsening
 3                    No data                   No data
 4                 Off course                   No data
 ..                       ...                       ...
 189                On course                   No data
 190               Off course             Some progress
 191                On course                   No data
 192                On course  No progress or worsening
 193                On course             Some progress

         under_5_wasting_track sodium_track rbp_female_track rbp_male_track
 0               Some progress   Off course       Off course     Off course  \
 1                   On course   Off course       Off course     Off course
 2                   On course   Off course       Off course     Off course
 3                     No data      No data        On course      On course
 4                   On course   Off course       Off course     Off course
 ..                        ...          ...              ...            ...
 189                   No data   Off course        On course     Off course
 190             Some progress   Off course       Off course     Off course
 191  No progress or worsening   Off course       Off course     Off course
 192                 On course   Off course       Off course     Off course
 193                 On course   Off course       Off course     Off course

     adult_fem_obesity_track adult_mal_obesity_track adult_fem_diabetes_track
 0                Off course              Off course               Off course  \
 1                Off course              Off course               Off course
 2                Off course              Off course               Off course
 3                Off course              Off course                On course
 4                Off course              Off course               Off course
 ..                      ...                     ...                      ...
 189              Off course              Off course               Off course
 190              Off course              Off course               Off course
 191              Off course              Off course               Off course
 192              Off course              Off course               Off course
 193              Off course              Off course            Some progress

     adult_mal_diabetes_track
 0                 Off course
 1                 Off course
 2                 Off course
 3                 Off course
 4                 Off course
 ..                       ...
 189               Off course
 190               Off course
 191               Off course
 192               Off course
 193               Off course

 [194 rows x 20 columns],
 'Region overview':                              region disaggregation  disagg.value   section
 0                            Africa            all           NaN  Overview  \
 1                              Asia            all           NaN  Overview
 2         Australia and New Zealand            all           NaN  Overview
 3                         Caribbean            all           NaN  Overview
 4                   Central America            all           NaN  Overview
 5                      Central Asia            all           NaN  Overview
 6                    Eastern Africa            all           NaN  Overview
 7                      Eastern Asia            all           NaN  Overview
 8                    Eastern Europe            all           NaN  Overview
 9                            Europe            all           NaN  Overview
 10                           Global            all           NaN  Overview
 11  Latin America and the Caribbean            all           NaN  Overview
 12                        Melanesia            all           NaN  Overview
 13                       Micronesia            all           NaN  Overview
 14                    Middle Africa            all           NaN  Overview
 15                    North America            all           NaN  Overview
 16                  Northern Africa            all           NaN  Overview
 17                 Northern America            all           NaN  Overview
 18                  Northern Europe            all           NaN  Overview
 19                          Oceania            all           NaN  Overview
 20                        Polynesia            all           NaN  Overview
 21                    South America            all           NaN  Overview
 22               South-eastern Asia            all           NaN  Overview
 23                  Southern Africa            all           NaN  Overview
 24                    Southern Asia            all           NaN  Overview
 25                  Southern Europe            all           NaN  Overview
 26                   Western Africa            all           NaN  Overview
 27                     Western Asia            all           NaN  Overview
 28                   Western Europe            all           NaN  Overview

     under_5_stunting_track_No data
 0                              NaN  \
 1                              4.0
 2                              1.0
 3                              6.0
 4                              NaN
 5                              NaN
 6                              NaN
 7                              NaN
 8                              3.0
 9                             25.0
 10                            39.0
 11                             6.0
 12                             NaN
 13                             2.0
 14                             NaN
 15                             1.0
 16                             NaN
 17                             1.0
 18                             9.0
 19                             3.0
 20                             NaN
 21                             NaN
 22                             NaN
 23                             NaN
 24                             NaN
 25                             7.0
 26                             NaN
 27                             4.0
 28                             6.0

     under_5_stunting_track_No progress or worsening
 0                                              10.0  \
 1                                               5.0
 2                                               NaN
 3                                               3.0
 4                                               1.0
 5                                               NaN
 6                                               4.0
 7                                               NaN
 8                                               NaN
 9                                               2.0
 10                                             28.0
 11                                              7.0
 12                                              2.0
 13                                              NaN
 14                                              2.0
 15                                              NaN
 16                                              2.0
 17                                              NaN
 18                                              NaN
 19                                              4.0
 20                                              2.0
 21                                              3.0
 22                                              1.0
 23                                              1.0
 24                                              1.0
 25                                              2.0
 26                                              1.0
 27                                              3.0
 28                                              NaN

     under_5_stunting_track_Some progress  under_5_stunting_track_On course
 0                                   38.0                               6.0  \
 1                                   18.0                              21.0
 2                                    NaN                               1.0
 3                                    2.0                               2.0
 4                                    6.0                               1.0
 5                                    NaN                               5.0
 6                                   12.0                               2.0
 7                                    NaN                               5.0
 8                                    2.0                               5.0
 9                                    3.0                              13.0
 10                                  74.0                              53.0
 11                                  11.0                               9.0
 12                                   2.0                               NaN
 13                                   2.0                               1.0
 14                                   6.0                               1.0
 15                                   NaN                               1.0
 16                                   4.0                               NaN
 17                                   NaN                               1.0
 18                                   NaN                               1.0
 19                                   4.0                               3.0
 20                                   1.0                               NaN
 21                                   3.0                               6.0
 22                                   7.0                               3.0
 23                                   3.0                               1.0
 24                                   5.0                               3.0
 25                                   1.0                               4.0
 26                                  13.0                               2.0
 27                                   6.0                               5.0
 28                                   NaN                               3.0

     anaemia_track_No data  anaemia_track_No progress or worsening  ...
 0                     NaN                                      37  ...  \
 1                     1.0                                      44  ...
 2                     NaN                                       2  ...
 3                     NaN                                      11  ...
 4                     NaN                                       5  ...
 5                     NaN                                       4  ...
 6                     NaN                                      15  ...
 7                     NaN                                       5  ...
 8                     1.0                                       9  ...
 9                     2.0                                      41  ...
 10                    3.0                                     161  ...
 11                    NaN                                      23  ...
 12                    NaN                                       4  ...
 13                    NaN                                       5  ...
 14                    NaN                                       4  ...
 15                    NaN                                       2  ...
 16                    NaN                                       5  ...
 17                    NaN                                       2  ...
 18                    NaN                                      10  ...
 19                    NaN                                      14  ...
 20                    NaN                                       3  ...
 21                    NaN                                       7  ...
 22                    NaN                                      10  ...
 23                    NaN                                       5  ...
 24                    NaN                                       9  ...
 25                    NaN                                      14  ...
 26                    NaN                                       8  ...
 27                    1.0                                      16  ...
 28                    1.0                                       8  ...

     adult_fem_obesity_track_On course  adult_mal_obesity_track_No data
 0                                 NaN                              NaN  \
 1                                 NaN                              NaN
 2                                 NaN                              NaN
 3                                 NaN                              NaN
 4                                 NaN                              NaN
 5                                 NaN                              NaN
 6                                 NaN                              NaN
 7                                 NaN                              NaN
 8                                 NaN                              NaN
 9                                 NaN                              NaN
 10                                NaN                              NaN
 11                                NaN                              NaN
 12                                NaN                              NaN
 13                                NaN                              NaN
 14                                NaN                              NaN
 15                                NaN                              NaN
 16                                NaN                              NaN
 17                                NaN                              NaN
 18                                NaN                              NaN
 19                                NaN                              NaN
 20                                NaN                              NaN
 21                                NaN                              NaN
 22                                NaN                              NaN
 23                                NaN                              NaN
 24                                NaN                              NaN
 25                                NaN                              NaN
 26                                NaN                              NaN
 27                                NaN                              NaN
 28                                NaN                              NaN

     adult_mal_obesity_track_Off course  adult_mal_obesity_track_On course
 0                                   53                                NaN  \
 1                                   48                                NaN
 2                                    2                                NaN
 3                                   13                                NaN
 4                                    8                                NaN

In [6]:
sheet_lengths = {}

# Iterate over the output above and calculate the length of each DataFrame
for sheet_name, df in df.items():
    sheet_lengths[sheet_name] = len(df)

# Print the lengths of each sheet
print(sheet_lengths)

{'Introduction': 3, 'Indicator descriptions': 127, 'Country overview': 194, 'Region overview': 29, 'Country child nutrition': 5178, 'Region child nutrition': 51, 'Country IYCF': 2775, 'Region IYCF': 25, 'Country adolescent': 762, 'Region adolescent': 116, 'Country adult': 4268, 'Region adult': 427, 'Country dietary needs': 193, 'Region dietary needs': 30, 'Country intervention': 1793, 'Country determinants': 194, 'Region determinants': 29, 'Country resources': 194, 'Region resources': 29, 'Country policy': 194, 'Region policy': 29, 'Country economics': 773, 'Region economics': 69, 'Country environment': 2157, 'Region environment': 351}